[package]
name = "ioc_container_rs"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "IoC container"
homepage = "https://github.com/kotletti/ioc_container_rs"
repository = "https://github.com/kotletti/ioc_container_rs"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
