[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true

[[bin]]
name = "initialize"
path = "src/initialize.rs"

[[bin]]
name = "readable"
path = "src/readable.rs"

[[bin]]
name = 'writeable'
path = 'src/writeable.rs'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ioc_container_rs = { path = "../ioc_container_rs" }
tests = { path = "../tests" }
tokio = { workspace = true }
